export default {
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "492895dd": [() => import(/* webpackChunkName: "492895dd" */ "@site/docs/client-only.md"), "@site/docs/client-only.md", require.resolveWeak("@site/docs/client-only.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "6c3524c4": [() => import(/* webpackChunkName: "6c3524c4" */ "@site/docs/sc-bindings.md"), "@site/docs/sc-bindings.md", require.resolveWeak("@site/docs/sc-bindings.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c2a887f8": [() => import(/* webpackChunkName: "c2a887f8" */ "@generated/docusaurus-plugin-content-docs/default/p/asteriq-docs-1d0.json"), "@generated/docusaurus-plugin-content-docs/default/p/asteriq-docs-1d0.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/asteriq-docs-1d0.json")],
  "c9fdda6d": [() => import(/* webpackChunkName: "c9fdda6d" */ "@site/docs/mappings.md"), "@site/docs/mappings.md", require.resolveWeak("@site/docs/mappings.md")],
  "d589d3a7": [() => import(/* webpackChunkName: "d589d3a7" */ "@site/docs/getting-started.md"), "@site/docs/getting-started.md", require.resolveWeak("@site/docs/getting-started.md")],
  "dec09136": [() => import(/* webpackChunkName: "dec09136" */ "@site/docs/settings.md"), "@site/docs/settings.md", require.resolveWeak("@site/docs/settings.md")],
  "eb38e6db": [() => import(/* webpackChunkName: "eb38e6db" */ "@site/docs/devices.md"), "@site/docs/devices.md", require.resolveWeak("@site/docs/devices.md")],
  "f013c2c3": [() => import(/* webpackChunkName: "f013c2c3" */ "@site/docs/network-forwarding.md"), "@site/docs/network-forwarding.md", require.resolveWeak("@site/docs/network-forwarding.md")],};
